// Edit graph content here. graph.js and styles.css handle behavior and visuals.
// Node info supports name, hebrewName, affiliation, and website for the info panel.
window.nbriGraphData = {
  nodes: [
    {
      id: "nbri",
      label: "NBRI",
      role: "Center",
      kind: "root",
      radius: 76,
      mass: 4.4,
      info: {
        name: "National Building Research Institute",
        hebrewName: "",
        website: "https://nbri.net.technion.ac.il/en/about/",
      },
    },

    {
      id: "rafael",
      label: "Prof. Rafael\nSacks",
      role: "Researcher",
      kind: "researcher",
      radius: 54,
      angle: -2.75,
      info: { name: "Rafael Sacks", hebrewName: "", website: "https://sacks.net.technion.ac.il/research/" },
    },
    {
      id: "huaquan",
      label: "Dr. Huaquan\nYing",
      role: "Researcher",
      kind: "researcher",
      radius: 54,
      angle: -1.9,
      info: { name: "Dr. Huaquan Ying", hebrewName: "", website: "https://scholar.google.com/citations?user=RLjm8pgAAAAJ&hl=en" },
    },
    {
      id: "tanya",
      label: "Dr. Tanya\nBloch",
      role: "Researcher",
      kind: "researcher",
      radius: 49,
      angle: -0.98,
      info: { name: "Tanya", hebrewName: "", website: "" },
    },
    {
      id: "researcher4",
      label: "Dr. Yiska\nGoldfeld",
      role: "Researcher",
      kind: "researcher",
      radius: 49,
      angle: 0.1,
      info: { name: "Dr. Yiska Goldfeld", hebrewName: "", website: "" },
    },
    {
      id: "researcher5",
      label: "Nicolò\nPollini",
      role: "Researcher",
      kind: "researcher",
      radius: 49,
      angle: 1.05,
      info: { name: "Nicolò Pollini", hebrewName: "", website: "" },
    },
    {
      id: "researcher6",
      label: "Dr. Semion\nZhutovsky",
      role: "Researcher",
      kind: "researcher",
      radius: 49,
      angle: 2.05,
      info: { name: "Dr. Semion Zhutovsky", hebrewName: "", website: "" },
    },

    {
      id: "universities",
      label: "Academic\nCollaborators",
      kind: "hub",
      radius: 58,
      angle: 2.8,
      info: { name: "Academic Collaborators", hebrewName: "", website: "" },
    },
    {
      id: "companies",
      label: "Industrial\nCollaborators",
      kind: "hub",
      radius: 58,
      angle: -0.42,
      info: { name: "Industrial Collaborators", hebrewName: "", website: "" },
    },
    {
      id: "tum",
      label: "TUM",
      kind: "partner",
      radius: 8,
      parent: "universities",
      branchDistance: 236,
      spread: -82,
      info: { name: "TUM", hebrewName: "", website: "" },
    },
    {
      id: "cambridge",
      label: "Cambridge",
      kind: "partner",
      radius: 8,
      parent: "universities",
      branchDistance: 188,
      spread: 0,
      info: { name: "Cambridge", hebrewName: "", website: "" },
    },
    {
      id: "dut",
      label: "DUT",
      kind: "partner",
      radius: 8,
      parent: "universities",
      branchDistance: 258,
      spread: 82,
      info: { name: "DUT", hebrewName: "", website: "" },
    },
    {
      id: "tidhar",
      label: "Tidhar\nLtd",
      kind: "partner",
      radius: 8,
      parent: "companies",
      branchDistance: 194,
      spread: -126,
      info: { name: "Tidhar Ltd", hebrewName: "", website: "" },
    },
    {
      id: "company2",
      label: "Company\n2",
      kind: "partner",
      radius: 8,
      parent: "companies",
      branchDistance: 238,
      spread: -42,
      info: { name: "Company 2", hebrewName: "", website: "" },
    },
    {
      id: "company3",
      label: "Company\n3",
      kind: "partner",
      radius: 8,
      parent: "companies",
      branchDistance: 210,
      spread: 42,
      info: { name: "Company 3", hebrewName: "", website: "" },
    },
    {
      id: "company4",
      label: "Company\n4",
      kind: "partner",
      radius: 8,
      parent: "companies",
      branchDistance: 252,
      spread: 126,
      info: { name: "Company 4", hebrewName: "", website: "" },
    },

    {
      id: "rafael-preview",
      label: "Seskin\nVirtual\nConstruction\nLab",
      kind: "preview",
      radius: 30,
      owner: "rafael",
      info: { name: "Digital Construction Lab", hebrewName: "", website: "" },
    },
    {
      id: "rafael-lab",
      label: "Seskin\nVirtual\nConstruction\nLab",
      kind: "lab",
      radius: 48,
      owner: "rafael",
      detail: true,
      info: { name: "Digital Construction Lab", hebrewName: "", website: "" },
    },
    {
      id: "rafael-member-1",
      label: "Lab\nMember 1",
      kind: "member",
      radius: 8,
      owner: "rafael",
      detail: true,
      branchDistance: 182,
      spread: -118,
      info: { name: "Lab Member 1", hebrewName: "", website: "" },
    },
    {
      id: "rafael-member-2",
      label: "Lab\nMember 2",
      kind: "member",
      radius: 8,
      owner: "rafael",
      detail: true,
      branchDistance: 236,
      spread: 0,
      info: { name: "Lab Member 2", hebrewName: "", website: "" },
    },
    {
      id: "rafael-member-3",
      label: "Lab\nMember 3",
      kind: "member",
      radius: 8,
      owner: "rafael",
      detail: true,
      branchDistance: 204,
      spread: 118,
      info: { name: "Lab Member 3", hebrewName: "", website: "" },
    },
    {
      id: "rafael-collaborator",
      label: "Maya\nLevin",
      kind: "collaborator",
      radius: 9,
      owner: "rafael",
      detail: true,
      branchDistance: 238,
      spread: 188,
      info: { name: "Maya Levin", hebrewName: "", website: "" },
    },
    {
      id: "rafael-workplace",
      label: "Tidhar\nLtd",
      kind: "workplace",
      radius: 9,
      owner: "rafael",
      detail: true,
      branchDistance: 162,
      info: { name: "Tidhar Ltd", hebrewName: "", website: "" },
    },

    {
      id: "huaquan-preview",
      label: "AI and Robotics\nfot Construction",
      kind: "preview",
      radius: 30,
      owner: "huaquan",
      info: { name: "AI for Built Assets Lab", hebrewName: "", website: "" },
    },
    {
      id: "huaquan-lab",
      label: "AI and Robotics\nfor Construction",
      kind: "lab",
      radius: 48,
      owner: "huaquan",
      detail: true,
      info: { name: "AI and Robotics for Construction", hebrewName: "", website: "" },
    },
    {
      id: "huaquan-member-1",
      label: "Zheng Zhao",
      kind: "member",
      radius: 8,
      owner: "huaquan",
      detail: true,
      branchDistance: 182,
      spread: -118,
      info: { name: "Zheng Zhao", hebrewName: "xxx", website: "xxx" },
    },
    {
      id: "huaquan-member-2",
      label: "Zikang Wang",
      kind: "member",
      radius: 8,
      owner: "huaquan",
      detail: true,
      branchDistance: 236,
      spread: 0,
      info: { name: "Zikang Wang", hebrewName: "xxx", website: "" },
    },
    {
      id: "huaquan-collaborator",
      label: "Liam\nCarter",
      kind: "collaborator",
      radius: 9,
      owner: "huaquan",
      detail: true,
      branchDistance: 238,
      spread: 188,
      info: { name: "Liam Carter", hebrewName: "", website: "" },
    },
    {
      id: "huaquan-workplace",
      label: "BuildTech\nPartners",
      kind: "workplace",
      radius: 9,
      owner: "huaquan",
      detail: true,
      branchDistance: 162,
      info: { name: "BuildTech Partners", hebrewName: "", website: "" },
    },

    {
      id: "tanya-preview",
      label: "Automation\nLab",
      kind: "preview",
      radius: 30,
      owner: "tanya",
      info: { name: "Automation Lab", hebrewName: "", website: "" },
    },
    {
      id: "tanya-lab",
      label: "Data Centric\nDesign and\nConstruction\nLab",
      kind: "lab",
      radius: 48,
      owner: "tanya",
      detail: true,
      info: { name: "Automation Lab", hebrewName: "", website: "" },
    },
    {
      id: "tanya-member-1",
      label: "Lab\nMember 1",
      kind: "member",
      radius: 8,
      owner: "tanya",
      detail: true,
      branchDistance: 182,
      spread: -118,
      info: { name: "Lab Member 1", hebrewName: "", website: "" },
    },
    {
      id: "tanya-member-2",
      label: "Lab\nMember 2",
      kind: "member",
      radius: 8,
      owner: "tanya",
      detail: true,
      branchDistance: 236,
      spread: 0,
      info: { name: "Lab Member 2", hebrewName: "", website: "" },
    },
    {
      id: "tanya-member-3",
      label: "Lab\nMember 3",
      kind: "member",
      radius: 8,
      owner: "tanya",
      detail: true,
      branchDistance: 204,
      spread: 118,
      info: { name: "Lab Member 3", hebrewName: "", website: "" },
    },
    {
      id: "tanya-collaborator",
      label: "Noa\nShalev",
      kind: "collaborator",
      radius: 9,
      owner: "tanya",
      detail: true,
      branchDistance: 238,
      spread: 188,
      info: { name: "Noa Shalev", hebrewName: "", website: "" },
    },
    {
      id: "tanya-workplace",
      label: "Company\n2",
      kind: "workplace",
      radius: 9,
      owner: "tanya",
      detail: true,
      branchDistance: 162,
      info: { name: "Company 2", hebrewName: "", website: "" },
    },

    {
      id: "researcher4-preview",
      label: "Intelligent\nStructures\nLaboratory",
      kind: "preview",
      radius: 30,
      owner: "researcher4",
      info: { name: "Intelligent Structures Laboratory", hebrewName: "", website: "" },
    },
    {
      id: "researcher4-lab",
      label: "Intelligent\nStructures\nLaboratory",
      kind: "lab",
      radius: 48,
      owner: "researcher4",
      detail: true,
      info: { name: "Intelligent Structures Laboratory", hebrewName: "", website: "" },
    },
    {
      id: "researcher4-member-1",
      label: "Lab\nMember 1",
      kind: "member",
      radius: 8,
      owner: "researcher4",
      detail: true,
      branchDistance: 182,
      spread: -118,
      info: { name: "Lab Member 1", hebrewName: "", website: "" },
    },
    {
      id: "researcher4-member-2",
      label: "Lab\nMember 2",
      kind: "member",
      radius: 8,
      owner: "researcher4",
      detail: true,
      branchDistance: 236,
      spread: 0,
      info: { name: "Lab Member 2", hebrewName: "", website: "" },
    },
    {
      id: "researcher4-member-3",
      label: "Lab\nMember 3",
      kind: "member",
      radius: 8,
      owner: "researcher4",
      detail: true,
      branchDistance: 204,
      spread: 118,
      info: { name: "Lab Member 3", hebrewName: "", website: "" },
    },
    {
      id: "researcher4-collaborator",
      label: "Ethan\nWu",
      kind: "collaborator",
      radius: 9,
      owner: "researcher4",
      detail: true,
      branchDistance: 238,
      spread: 188,
      info: { name: "Ethan Wu", hebrewName: "", website: "" },
    },
    {
      id: "researcher4-workplace",
      label: "DUT\nSpinout",
      kind: "workplace",
      radius: 9,
      owner: "researcher4",
      detail: true,
      branchDistance: 162,
      info: { name: "DUT Spinout", hebrewName: "", website: "" },
    },

    {
      id: "researcher5-preview",
      label: "MDO\nResearch\nGroup",
      kind: "preview",
      radius: 30,
      owner: "researcher5",
      info: { name: "MDO research group", hebrewName: "", website: "" },
    },
    {
      id: "researcher5-lab",
      label: "MDO\nResearch\nGroup",
      kind: "lab",
      radius: 48,
      owner: "researcher5",
      detail: true,
      info: { name: "MDO research group", hebrewName: "", website: "" },
    },
    {
      id: "researcher5-member-1",
      label: "Lab\nMember 1",
      kind: "member",
      radius: 8,
      owner: "researcher5",
      detail: true,
      branchDistance: 182,
      spread: -118,
      info: { name: "Lab Member 1", hebrewName: "", website: "" },
    },
    {
      id: "researcher5-member-2",
      label: "Lab\nMember 2",
      kind: "member",
      radius: 8,
      owner: "researcher5",
      detail: true,
      branchDistance: 236,
      spread: 0,
      info: { name: "Lab Member 2", hebrewName: "", website: "" },
    },
    {
      id: "researcher5-member-3",
      label: "Lab\nMember 3",
      kind: "member",
      radius: 8,
      owner: "researcher5",
      detail: true,
      branchDistance: 204,
      spread: 118,
      info: { name: "Lab Member 3", hebrewName: "", website: "" },
    },
    {
      id: "researcher5-collaborator",
      label: "Ava\nSingh",
      kind: "collaborator",
      radius: 9,
      owner: "researcher5",
      detail: true,
      branchDistance: 238,
      spread: 188,
      info: { name: "Ava Singh", hebrewName: "", website: "" },
    },
    {
      id: "researcher5-workplace",
      label: "Company\n3",
      kind: "workplace",
      radius: 9,
      owner: "researcher5",
      detail: true,
      branchDistance: 162,
      info: { name: "Company 3", hebrewName: "", website: "" },
    },

    {
      id: "researcher6-preview",
      label: "Laboratory\nof Alternative\nBinders",
      kind: "preview",
      radius: 30,
      owner: "researcher6",
      info: { name: "Laboratory of Alternative Binders", hebrewName: "", website: "" },
    },
    {
      id: "researcher6-lab",
      label: "Laboratory\nof Alternative\nBinders",
      kind: "lab",
      radius: 48,
      owner: "researcher6",
      detail: true,
      info: { name: "Laboratory of Alternative Binders", hebrewName: "", website: "" },
    },
    {
      id: "researcher6-member-1",
      label: "Lab\nMember 1",
      kind: "member",
      radius: 8,
      owner: "researcher6",
      detail: true,
      branchDistance: 182,
      spread: -118,
      info: { name: "Lab Member 1", hebrewName: "", website: "" },
    },
    {
      id: "researcher6-member-2",
      label: "Lab\nMember 2",
      kind: "member",
      radius: 8,
      owner: "researcher6",
      detail: true,
      branchDistance: 236,
      spread: 0,
      info: { name: "Lab Member 2", hebrewName: "", website: "" },
    },
    {
      id: "researcher6-member-3",
      label: "Lab\nMember 3",
      kind: "member",
      radius: 8,
      owner: "researcher6",
      detail: true,
      branchDistance: 204,
      spread: 118,
      info: { name: "Lab Member 3", hebrewName: "", website: "" },
    },
    {
      id: "researcher6-collaborator",
      label: "Oren\nTal",
      kind: "collaborator",
      radius: 9,
      owner: "researcher6",
      detail: true,
      branchDistance: 238,
      spread: 188,
      info: { name: "Oren Tal", hebrewName: "", website: "" },
    },
    {
      id: "researcher6-workplace",
      label: "TUM\nVenture",
      kind: "workplace",
      radius: 9,
      owner: "researcher6",
      detail: true,
      branchDistance: 162,
      info: { name: "TUM Venture", hebrewName: "", website: "" },
    },
  ],

  links: [
    { source: "nbri", target: "rafael", relation: "affiliate", strength: 0.028, distance: 215 },
    { source: "nbri", target: "huaquan", relation: "affiliate", strength: 0.028, distance: 215 },
    { source: "nbri", target: "tanya", relation: "affiliate", strength: 0.028, distance: 215 },
    { source: "nbri", target: "researcher4", relation: "affiliate", strength: 0.028, distance: 215 },
    { source: "nbri", target: "researcher5", relation: "affiliate", strength: 0.028, distance: 215 },
    { source: "nbri", target: "researcher6", relation: "affiliate", strength: 0.028, distance: 215 },
    { source: "nbri", target: "universities", relation: "cooperate", strength: 0.024, distance: 275 },
    { source: "nbri", target: "companies", relation: "cooperate", strength: 0.024, distance: 275 },
    { source: "universities", target: "tum", relation: "cooperate", strength: 0.04, distance: 156 },
    { source: "universities", target: "cambridge", relation: "cooperate", strength: 0.04, distance: 156 },
    { source: "universities", target: "dut", relation: "cooperate", strength: 0.04, distance: 156 },
    { source: "companies", target: "tidhar", relation: "cooperate", strength: 0.04, distance: 156 },
    { source: "companies", target: "company2", relation: "cooperate", strength: 0.04, distance: 156 },
    { source: "companies", target: "company3", relation: "cooperate", strength: 0.04, distance: 156 },
    { source: "companies", target: "company4", relation: "cooperate", strength: 0.04, distance: 156 },

    { source: "rafael", target: "rafael-preview", relation: "affiliate", owner: "rafael", preview: true, strength: 0.02, distance: 102 },
    { source: "rafael", target: "rafael-lab", relation: "affiliate", owner: "rafael", detail: true, strength: 0.05, distance: 134 },
    { source: "rafael-lab", target: "rafael-member-1", relation: "affiliate", owner: "rafael", detail: true, strength: 0.048, distance: 154 },
    { source: "rafael-lab", target: "rafael-member-2", relation: "affiliate", owner: "rafael", detail: true, strength: 0.048, distance: 154 },
    { source: "rafael-lab", target: "rafael-member-3", relation: "affiliate", owner: "rafael", detail: true, strength: 0.048, distance: 154 },
    { source: "rafael", target: "rafael-collaborator", relation: "cooperate", owner: "rafael", detail: true, strength: 0.044, distance: 156 },
    { source: "rafael-collaborator", target: "rafael-workplace", relation: "affiliate", owner: "rafael", detail: true, strength: 0.034, distance: 104 },

    { source: "huaquan", target: "huaquan-preview", relation: "affiliate", owner: "huaquan", preview: true, strength: 0.02, distance: 102 },
    { source: "huaquan", target: "huaquan-lab", relation: "affiliate", owner: "huaquan", detail: true, strength: 0.05, distance: 134 },
    { source: "huaquan-lab", target: "huaquan-member-1", relation: "affiliate", owner: "huaquan", detail: true, strength: 0.048, distance: 154 },
    { source: "huaquan-lab", target: "huaquan-member-2", relation: "affiliate", owner: "huaquan", detail: true, strength: 0.048, distance: 154 },
    { source: "huaquan", target: "huaquan-collaborator", relation: "cooperate", owner: "huaquan", detail: true, strength: 0.044, distance: 156 },
    { source: "huaquan-collaborator", target: "huaquan-workplace", relation: "affiliate", owner: "huaquan", detail: true, strength: 0.034, distance: 104 },

    { source: "tanya", target: "tanya-preview", relation: "affiliate", owner: "tanya", preview: true, strength: 0.02, distance: 102 },
    { source: "tanya", target: "tanya-lab", relation: "affiliate", owner: "tanya", detail: true, strength: 0.05, distance: 134 },
    { source: "tanya-lab", target: "tanya-member-1", relation: "affiliate", owner: "tanya", detail: true, strength: 0.048, distance: 154 },
    { source: "tanya-lab", target: "tanya-member-2", relation: "affiliate", owner: "tanya", detail: true, strength: 0.048, distance: 154 },
    { source: "tanya-lab", target: "tanya-member-3", relation: "affiliate", owner: "tanya", detail: true, strength: 0.048, distance: 154 },
    { source: "tanya", target: "tanya-collaborator", relation: "cooperate", owner: "tanya", detail: true, strength: 0.044, distance: 156 },
    { source: "tanya-collaborator", target: "tanya-workplace", relation: "affiliate", owner: "tanya", detail: true, strength: 0.034, distance: 104 },

    { source: "researcher4", target: "researcher4-preview", relation: "affiliate", owner: "researcher4", preview: true, strength: 0.02, distance: 102 },
    { source: "researcher4", target: "researcher4-lab", relation: "affiliate", owner: "researcher4", detail: true, strength: 0.05, distance: 134 },
    { source: "researcher4-lab", target: "researcher4-member-1", relation: "affiliate", owner: "researcher4", detail: true, strength: 0.048, distance: 154 },
    { source: "researcher4-lab", target: "researcher4-member-2", relation: "affiliate", owner: "researcher4", detail: true, strength: 0.048, distance: 154 },
    { source: "researcher4-lab", target: "researcher4-member-3", relation: "affiliate", owner: "researcher4", detail: true, strength: 0.048, distance: 154 },
    { source: "researcher4", target: "researcher4-collaborator", relation: "cooperate", owner: "researcher4", detail: true, strength: 0.044, distance: 156 },
    { source: "researcher4-collaborator", target: "researcher4-workplace", relation: "affiliate", owner: "researcher4", detail: true, strength: 0.034, distance: 104 },

    { source: "researcher5", target: "researcher5-preview", relation: "affiliate", owner: "researcher5", preview: true, strength: 0.02, distance: 102 },
    { source: "researcher5", target: "researcher5-lab", relation: "affiliate", owner: "researcher5", detail: true, strength: 0.05, distance: 134 },
    { source: "researcher5-lab", target: "researcher5-member-1", relation: "affiliate", owner: "researcher5", detail: true, strength: 0.048, distance: 154 },
    { source: "researcher5-lab", target: "researcher5-member-2", relation: "affiliate", owner: "researcher5", detail: true, strength: 0.048, distance: 154 },
    { source: "researcher5-lab", target: "researcher5-member-3", relation: "affiliate", owner: "researcher5", detail: true, strength: 0.048, distance: 154 },
    { source: "researcher5", target: "researcher5-collaborator", relation: "cooperate", owner: "researcher5", detail: true, strength: 0.044, distance: 156 },
    { source: "researcher5-collaborator", target: "researcher5-workplace", relation: "affiliate", owner: "researcher5", detail: true, strength: 0.034, distance: 104 },

    { source: "researcher6", target: "researcher6-preview", relation: "affiliate", owner: "researcher6", preview: true, strength: 0.02, distance: 102 },
    { source: "researcher6", target: "researcher6-lab", relation: "affiliate", owner: "researcher6", detail: true, strength: 0.05, distance: 134 },
    { source: "researcher6-lab", target: "researcher6-member-1", relation: "affiliate", owner: "researcher6", detail: true, strength: 0.048, distance: 154 },
    { source: "researcher6-lab", target: "researcher6-member-2", relation: "affiliate", owner: "researcher6", detail: true, strength: 0.048, distance: 154 },
    { source: "researcher6-lab", target: "researcher6-member-3", relation: "affiliate", owner: "researcher6", detail: true, strength: 0.048, distance: 154 },
    { source: "researcher6", target: "researcher6-collaborator", relation: "cooperate", owner: "researcher6", detail: true, strength: 0.044, distance: 156 },
    { source: "researcher6-collaborator", target: "researcher6-workplace", relation: "affiliate", owner: "researcher6", detail: true, strength: 0.034, distance: 104 },
  ],
};
